=== epics-extensions/ea-cpp/apps/common/pva/xml/serverconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the XML-RPC Data Server Configuration -->
<!ELEMENT serverconfig (archive+)>
<!ELEMENT archive (key,name,path)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (#PCDATA)>

=== epics-extensions/ea-cpp/apps/common/pva/xml/serverconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serverconfig SYSTEM "serverconfig.dtd">
<serverconfig>
<archive>
     <key>1</key>
     <name>Vacuum</name>
     <path>/home/data/vac/index</path>
</archive>
<archive>
     <key>2</key>
     <name>RF-LLRF</name>
     <path>/home/data/llrf/index</path>
</archive>
</serverconfig>
